# Generated by Django 6.0.4 on 2026-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Interest Sent', 'Interest Sent'), ('Need Callback', 'Need Callback'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
