# Generated by Django 5.0.6 on 2026-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_enquiry_updated_at_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Interest Sent', 'Interest Sent'), ('Need Callback', 'Need Callback'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Replied', 'Replied'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
