# Generated by Django 5.0.6 on 2026-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_enquiry_admin_reply_enquiry_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='reply_seen',
            field=models.BooleanField(default=False),
        ),
    ]
